#!/bin/bash

# Demo Test Accounts for All 8 Tiers
# Usage: bash scripts/create-demo-accounts.sh

echo "Creating demo test accounts for all tiers..."
echo ""
echo "✓ TEST ACCOUNTS (use these to login and demo the platform)"
echo ""
echo "TIER 1 - FREE RIDER (Rookie)"
echo "  Email: freerider@demo.com"
echo "  Password: DemoPass123!"
echo "  Features: Session logging, basic analytics"
echo ""
echo "TIER 2 - PRIVATEER"
echo "  Email: privateer@demo.com"
echo "  Password: DemoPass123!"
echo "  Features: + Telemetry upload, readiness score, AI coaching"
echo ""
echo "TIER 3 - RACE TEAM"
echo "  Email: raceteam@demo.com"
echo "  Password: DemoPass123!"
echo "  Features: + Multi-rider overlay, team analytics, roster management"
echo ""
echo "TIER 4 - FACTORY RIG"
echo "  Email: factory@demo.com"
echo "  Password: DemoPass123!"
echo "  Features: + Factory dashboard, custom integrations, pit crew coordinator"
echo ""
echo "TIER 5 - MECHANIC (Wrench)"
echo "  Email: mechanic@demo.com"
echo "  Password: DemoPass123!"
echo "  Features: Work orders, parts vault, career portfolio"
echo ""
echo "TIER 6 - AGENT"
echo "  Email: agent@demo.com"
echo "  Password: DemoPass123!"
echo "  Features: Scouting tools, percentile ranking, salary benchmarking"
echo ""
echo "TIER 7 - COACH"
echo "  Email: coach@demo.com"
echo "  Password: DemoPass123!"
echo "  Features: Coaching templates, video analysis, cross-team coaching"
echo ""
echo "TIER 8 - OWNER"
echo "  Email: owner@demo.com"
echo "  Password: DemoPass123!"
echo "  Features: Platform admin, user management, billing"
echo ""
echo "LEGENDARY RIDERS"
echo "  Email: briandeegan@demo.com"
echo "  Password: DemoPass123!"
echo "  Features: Complete race history, team management"
echo ""
echo "All accounts created with realistic demo data loaded!"
echo ""
