import { LegalDocLayout, LegalSection } from '@/components/legal/legal-doc-layout'

export const metadata = {
  title: 'Intellectual Property & DMCA',
  description: 'Motorsport Data intellectual property rights, copyright policy, and DMCA takedown procedure.',
  alternates: { canonical: 'https://motorsportsdata.io/legal/ip' },
}

export default function IPPage() {
  return (
    <LegalDocLayout
      title="Intellectual Property & DMCA"
      version="1.0"
      effectiveDate="July 2026"
      intro="This policy describes who owns what on the Platform, how we handle copyright claims, and how to submit a DMCA takedown notice or counter-notice."
    >
      <LegalSection n={1} title="Platform IP — What We Own">
        <p>
          Motorsport Data owns all rights in the Platform itself: the software, source code, user
          interface designs, graphics, text, AI models, prompts, model weights, and the selection
          and arrangement of all content we create. These are protected by copyright, trademark,
          trade secret, and other applicable laws. The names and marks{' '}
          <strong className="text-zinc-100">Motorsport Data</strong>,{' '}
          <strong className="text-zinc-100">Rig Doctor</strong>,{' '}
          <strong className="text-zinc-100">Free Rider</strong>, and{' '}
          <strong className="text-zinc-100">Command Rig</strong>, along with their associated logos,
          are trademarks of Motorsport Data. You may not use them without our prior written consent.
        </p>
      </LegalSection>

      <LegalSection n={2} title="User Content — What You Own">
        <p>
          You retain full ownership of the raw content you upload: vehicle setups, session data,
          telemetry, images, and related materials. By uploading, you grant Motorsport Data a
          limited license to host, process, and display that content solely to operate the Platform
          and to share it with accounts you authorize. You also grant us a license to create
          anonymized, aggregated data as described in our{' '}
          <a href="/legal/data-consent" className="text-lime-400 hover:underline">
            Data Sharing &amp; Consent
          </a>{' '}
          policy. We do not claim ownership of your raw uploaded content.
        </p>
      </LegalSection>

      <LegalSection n={3} title="Coach and Third-Party IP">
        <p>
          Coaches and other users may store proprietary training programs, curricula, and materials
          on the Platform. Such materials remain the property of the coach or the party that owns
          them. Motorsport Data acts solely as custodian. We do not claim ownership of third-party
          materials stored on the Platform and will not disclose them except as directed by the
          owner or required by law. You may not access, copy, or use another user&apos;s proprietary
          materials without their authorization.
        </p>
      </LegalSection>

      <LegalSection n={4} title="AI-Generated Output">
        <p>
          Output generated by Platform AI features (including Rig Doctor) is derived from our
          proprietary models. We own the models and prompts; you own the output generated from your
          own data and prompts in the context of your account. AI output is provided for
          informational purposes only and is not a substitute for professional judgment.
        </p>
      </LegalSection>

      <LegalSection n={5} title="Prohibited Uses of Our IP">
        <ul className="list-inside list-disc space-y-2">
          <li>Copying, reproducing, or distributing our software, designs, or content without permission;</li>
          <li>Reverse engineering, decompiling, or extracting our source code, models, or model weights;</li>
          <li>Scraping or bulk-extracting data from the Platform by automated means;</li>
          <li>Using our trademarks or branding in a way that suggests affiliation or endorsement without consent;</li>
          <li>Using Platform content or AI output to train or improve a competing product or external model.</li>
        </ul>
      </LegalSection>

      <LegalSection n={6} title="DMCA Takedown — Submitting a Notice">
        <p>
          If you believe content on the Platform infringes your copyright, you may submit a written
          notice to our designated DMCA agent. Your notice must include:
        </p>
        <ol className="mt-2 list-inside list-decimal space-y-2">
          <li>A description of the copyrighted work you claim has been infringed;</li>
          <li>A description of where the allegedly infringing material is located on the Platform (URL or sufficient detail);</li>
          <li>Your contact information (name, address, telephone, email);</li>
          <li>A statement that you have a good-faith belief that the use is not authorized by the copyright owner, its agent, or the law;</li>
          <li>A statement that the information in your notice is accurate and, under penalty of perjury, that you are the copyright owner or authorized to act on their behalf;</li>
          <li>Your physical or electronic signature.</li>
        </ol>
        <p className="mt-4">
          Send notices to:{' '}
          <a href="mailto:legal@motorsportsdata.io" className="text-lime-400 hover:underline">
            legal@motorsportsdata.io
          </a>{' '}
          — subject line: <span className="font-mono text-sm text-zinc-300">DMCA Notice</span>.
        </p>
      </LegalSection>

      <LegalSection n={7} title="DMCA Counter-Notice">
        <p>
          If you believe content was removed in error, you may submit a counter-notice to the same
          address. Your counter-notice must include: identification of the removed material and its
          former location; a statement under penalty of perjury that you have a good-faith belief
          the material was removed by mistake or misidentification; your name, address, telephone,
          and email; and your consent to the jurisdiction of the federal court in your district (or,
          if outside the US, any judicial district in which Motorsport Data may be found), and your
          physical or electronic signature.
        </p>
        <p className="mt-4">
          We will forward counter-notices to the original complainant. If no action is taken within
          10&ndash;14 business days, we may restore the content.
        </p>
      </LegalSection>

      <LegalSection n={8} title="Repeat Infringers">
        <p>
          Motorsport Data will terminate accounts of users who are determined to be repeat
          infringers in appropriate circumstances, consistent with the Digital Millennium Copyright
          Act.
        </p>
      </LegalSection>

      <LegalSection n={9} title="Contact">
        <p>
          For all IP and copyright matters:{' '}
          <a href="mailto:legal@motorsportsdata.io" className="text-lime-400 hover:underline">
            legal@motorsportsdata.io
          </a>
        </p>
      </LegalSection>
    </LegalDocLayout>
  )
}
